version: "3"
services:


  # FAIR Data Point client	
  fdp_client:
    image: fairdata/fairdatapoint-client:1.15.0
    hostname: fdpclient
    restart: always
    environment:
      FDP_HOST: fdp
    volumes:
      - ./fdp/variables.scss:/src/scss/custom/_variables.scss:ro
      - ./fdp/assets:/usr/share/nginx/html/assets:ro
      - ./fdp/favicon.ico:/usr/share/nginx/html/favicon.ico:ro
    depends_on:
      - fdp
    ports:
      - 7070:80  # You should/must close this port, if you are using hitch
    networks:
      - default


  graphdb:
    image: graphdb:local
    restart: always
    hostname: graphdb
    ports:
      - 7200:7200
    volumes:
      - $PWD/graphdb:/opt/graphdb/home
    networks:
      - default

  fdp:
    image: fairdata/fairdatapoint:1.15.0
    restart: always
    volumes:
      - ./fdp/application.yml:/fdp/application.yml:ro
    depends_on:
      - mongo
      - graphdb
    networks:
      - default
        

  # Mongo for FDP server    
  mongo:
    image: mongo:4.2.3
    restart: always
    volumes:
      - mongo-data:/data/db
      - mongo-init:/docker-entrypoint-initdb.d/
    networks:
      - default


  ldp:
    image: markw/ldp_server:2022
    volumes:
      - ./ldp:/database
    ports:
      - 1111:1111
      - 8890:8890
    networks:
      - default


volumes:
  mongo-data:
    external: true
  mongo-init:
    external: true
  fdp-server:
    external: true

